### PR TITLE
add changelog

### LINKED ISSUE #472: Generate changelog
### Versions

Please provide your platform details:

| Software | Information |
| :--- | :--- |
| Operating System| e.g. `Ubuntu` |
| OS Version| e.g. `14.04` |
| java -version | e.g. `1.8.0_141` | 
| psql --version | e.g. `9.6.3` |
| gradle --version | e.g. `3.4` |

Software versions in the [Let's start](/README.md#lets-start) section in the README.

### Description

What should happen and what happens instead  
or short description of the feature request

### Error log

```
If you have an error log, please paste it here.
```

### PR DESCRIPTION
**Pull request by lorenaqendro**
### Description
Add changelog.
Fixes #472

### Checklist

- [ ] ~~Created new test(s) (if applicable)~~
- [ ] ~~Updated the README / documentation (if applicable)~~

### CODE REVIEW

**Comment by eddiejaoude** [comment]
This could be auto generated from the `git` data. I will raise an issue for it, so you can review later.

**Comment by eddiejaoude** [comment]
An issue already exists, I added a link to an example tool, here is the issue  https://github.com/FutureCitiesCatapult/TomboloDigitalConnector/issues/472

**Comment by lorenaqendro** [comment]
@eddiejaoude Thank you! Yes, that would be our next step for the changelog generation.

**Comment by eddiejaoude** [comment]
👍

**Pull request merged**
